#! /bin/sh                                              
                                                        
pgrep -x sxhkd > /dev/null || sxhkd &                   
                                                        
bspc monitor -d 1 2 3 4 5 6 7 8 9 10                    
                                                        
bspc config border_width         1                      
bspc config window_gap          16                      
                                                        
bspc config split_ratio          0.52                   
bspc config borderless_monocle   true                   
bspc config gapless_monocle      true                   
bspc config focus_follows_pointer true                  
                                                        
### Autostart ###                                       
                                                        
sxhkd &                                                 
picom --config $HOME/.config/picom/picom.conf &         
feh --bg-fill $HOME/Pictures/5.png &                    
dunst &                                                 
$HOME/.config/polybar/launch.sh &                       
otd-daemon &                                            
